### PR TITLE
Move twitch URLs to appropriate class, fix #51

### LINKED ISSUE #51: Twitch streams won't play if the URL has capitalized characters
Twitch streams will break and stop playing if the URL has any capitalized character. 
For example: **https://www.twitch.tv/thecoffeeelf** will play just fine. But **https://www.twitch.tv/TheCoffeeElf** would fail to play.

### PR DESCRIPTION
**Pull request by GravelCZ**

### CODE REVIEW

**Review by devoxin — APPROVED** [review]

File: main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java [hunk 1]
```diff
@@ -70,7 +70,8 @@ public String getSourceName() {
 
     @Override
     public AudioItem loadItem(AudioPlayerManager manager, AudioReference reference) {
-        String streamName = getChannelIdentifierFromUrl(reference.identifier);
+	    // Using root because the turkish lowercase "i" does not have the little dot above the letter when defaulted
+        String streamName = getChannelIdentifierFromUrl(reference.identifier).toLowerCase(Locale.ROOT);
```
Comment (devoxin) [inline main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java:74]: Actually on second thoughts, it's probably better to lowercase after the null check otherwise this could throw a `NullPointerException`.

**Review by devoxin — CHANGES_REQUESTED** [review]

File: main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java (hunk 1 above)
Comment (GravelCZ) [reply main/src/main/java/com/sedmelluq/discord/lavaplayer/source/twitch/TwitchStreamAudioSourceManager.java:74]: Yeah true

**Review by devoxin — APPROVED** [review]
